### ISSUE TITLE
GMB API Access

### ISSUE THREAD

**Issue by kriiv** [scottybo/Laravel-Google-My-Business#11]
I know this is somewhat irrelevant but I'd appreciate any assistance that you may have.
Any tips on getting approved for the GMB API? 

I am applying as a software dev to provide a software product around the GMB API but am getting rejected. How are you getting your access? Are you part of an agency? Or perhaps going to be using this in-house?

Thanks

**Comment by scottybo** [comment]
I use it as part of a social media scheduling tool - we post to places such as Facebook, LinkedIn Twitter etc, and one of the platforms includes Google My Business. Perhaps our use case was different to yours?
