### ISSUE TITLE
Method updateReply

### ISSUE THREAD

**Issue by DivOverlow** [scottybo/Laravel-Google-My-Business#15]
Hi! I am actively using your product for which I am very grateful. However, when the reply is updated, there is an error with the argument  Google_Service_MyBusiness_ReviewReply $postBody

`public function updateReply($name, Google_Service_MyBusiness_ReviewReply $postBody, $optParams = array())`

the fact is that it is not possible to get an instance of the class - Google_Service_MyBusiness_ReviewReply
public function getReviewReply() - return is array.

My example:
    ```
public function updateReply($name, $postBody): \Scottybo\LaravelGoogleMyBusiness\Google_Service_MyBusiness_ReviewReply
    {
        $review = $this->googleMyBusiness->accounts_locations_reviews->get($name);
        $reply = $review->getReviewReply();
        $reply['comment'] = $postBody;

        return $this->googleMyBusiness->accounts_locations_reviews->updateReply($name, $reply);
    }

```
to avoid the problem I had to change the 2 attribute  to array - array  $postBody
I will be grateful for any information. Thank you!

**Comment by scottybo** [comment]
Due to Google My Business deprecating this API in April, I will not be maintaining this package anymore. I'd recommend taking a look at the upcoming changes from Google
