### ISSUE TITLE
upgrade to the new v1 endpoints -- Enhancement

### ISSUE THREAD

**Issue by Arametheus** [scottybo/Laravel-Google-My-Business#16]
I was wondering will this package be upgraded for the new Endpoints v1 before the old endpoints are depreciated at the end of April?

**Comment by Arametheus** [comment]
Just wanted to add to this now getting this error returned when getting locations.   "errorDetails": [ { "message": "This API will soon be deprecated. Please migrate all the usages to My Business Account Management API - https://developers.google.com/my-business/reference/accountmanagement/rest" } ]

**Comment by scottybo** [comment]
The library will still work in some areas, but in others you'll need to migrate to using the main Google API client (as referenced in the docs). You're going to need to change your code, and eventually this library will no longer be required as it'll all be in the main Google API client (albeit with different functions / approaches).
