### ISSUE TITLE
Can't get report data

### ISSUE THREAD

**Issue by scottmkroberts** [scottybo/Laravel-Google-My-Business#4]
Hi, 

We are using this to access google my business API to access location insights for individual locations we manage. 

Now currently the path to this api endpoint is in the following location
 
**vendor\scottybo\laravel-google-my-business\src\GoogleMyBusiness.php
line =  460**

is  `'path' => 'v4/{+name}/locations:reportInsights',`

This results in no data unless we change the path to be `'path' => 'v4/accounts/{+name}/locations:reportInsights',`

now looking at the mybusiness_google_rest_v4p4.json file 

` "reportInsights": {
              "id": "mybusiness.accounts.locations.reportInsights",
              "path": "v4/{+name}/locations:reportInsights",
              "flatPath": "v4/accounts/{accountsId}/locations:reportInsights",
              "httpMethod": "POST",
              "parameters": {
                "name": {
                  "description": "The account resource name.",
                  "location": "path",
                  "required": true,
                  "pattern": "^accounts\/[^\/]+$",
                  "type": "string"
                }
              },`

You will see the flat path is correct and would result in the data but we can't swap the library to use this. I am not sure after research the difference between *path* and *flatPath*

But unless we include '/accounts' in the path we are unable to successfully return results. 

I am going to fork the library to change the path in the following location

vendor\scottybo\laravel-google-my-business\src\GoogleMyBusiness.php
line for 460

But I really don't know if this is the right solution and where the bug is, Google, this library or the way we are accessing reportInsights in our code base. 

Any insight would be helpful and I am happy to do the leg work if something needs changing.

**Comment by scottybo** [comment]
This library itself comes from Google, so it might be worth jumping onto the Google community forums to clarify what the correct answer is, and then we can update this package if required

**Comment by scottmkroberts** [comment]
Thanks for replying and Will do, I will reply back here with what I find the answer to be. My fork with that update is now allowing us to pull the insights, so I will try to gather clarification from them.

**Comment by scottybo** [comment]
Ok, sounds a plan - I'll leave this issue open for now

**Comment by scottybo** [comment]
@scottmkroberts how did you get on? :)

**Comment by scottmkroberts** [comment]
Hi sorry for the late reply, We did get a response back from google I will include it here;

> As per the method accounts.locations:reportInsights  the request should be:
> 
> POST https://mybusiness.googleapis.com/v4/{name=accounts/*}/locations:reportInsights 
> 
> While the naming might seem contrary they are one in the same. When you run the method accounts.list the field name for your account is in the format of accounts/{accountId}. Both ways are correct, the only difference is how the content is described. 
> 
> When in doubt we recommend referencing the REST resource for any request including the URI, query parameters, and the request body.

but it still was not clear enough, as we will have to do what we are doing. I need to dive into it deeper I am hoping to have a bit more time in December to do that then I should have a clear idea and response. 

Again apologies for the delay.

**Comment by scottybo** [comment]
No problem, thanks for the update - will be great to learn more once you've figured it out :)
