### ISSUE TITLE
How does this differ from Socialite?

### ISSUE THREAD

**Issue by RyanPaiva56** [scottybo/Laravel-Google-My-Business#5]
Forgive me for my basic understanding, but wouldn't this be similar to socialite in terms of authentication? Does it work off the same token? So if we have Google+ login for Socialite, can we use that token with this for authenticating requests?

**Comment by scottybo** [comment]
You could use Socialite to authenticate, as long as you use the right scopes.

However, you would still need the GMB library to do anything useful with a business listing - Socialite is purely for authentication.
