### ISSUE TITLE
Call to undefined method PulkitJalan\Google\Facades\Google::createAuthUrl()

### ISSUE THREAD

**Issue by tancincozach** [scottybo/Laravel-Google-My-Business#8]
![image](https://user-images.githubusercontent.com/5601634/73717859-e8b21a80-4755-11ea-8e1a-a433575640db.png)

I have already configured all the needed configuration . Can anyone help me regarding about this?

**Comment by prolonginc** [comment]
i am in the same boat as you @tancincozach  have you figured this out. im at a point where imma go to use the actual google client.

**Comment by prolonginc** [comment]
i did the following and it worked
 ```php
 $googleClient = new Google\Client($googleConfig);
$loginUrl = $googleClient->createAuthUrl();
```

**Comment by scottybo** [comment]
Thanks @prolonginc
